# Generated by Django 3.1.1 on 2020-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200926_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pf1.jpeg', null=True, upload_to=''),
        ),
    ]
